/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.5.0
 *
 * Project: 'SDS_Player_fs_CMSIS.Release+ARMCLANG' 
 * Target:  'Release+ARMCLANG' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55M1.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
        #define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* ARM::SDS:Buffer@1.0.0 */
#define RTE_SDS_BUFFER                  /* Synchronous Data Stream (Buffer) */
/* ARM::SDS:IO:File System&MDK FS@1.2.0 */
#define RTE_SDS_IO                       /* Synchronous Data Stream Input/Output */
        #define RTE_SDS_IO_FILE_SYSTEM           /* Synchronous Data Stream Input/Output (File System) */
        #define RTE_SDS_IO_FILE_SYSTEM_MDK_FS    /* Synchronous Data Stream Input/Output (File System - MDK FS) */
/* ARM::SDS:Player&CMSIS-RTOS2@2.0.0 */
#define RTE_SDS_PLAYER                  /* Synchronous Data Stream Player */
/* Keil::CMSIS-Compiler:File Interface:MDK-MW File System@1.0.1 */
#define RTE_CMSIS_Compiler_File_Interface        /* CMSIS-Compiler File Interface */
        #define RTE_CMSIS_Compiler_File_Interface_MDK_MW /* CMSIS-Compiler File Interface: MDK-Middleware File System */
/* Keil::File System&MDK:CORE@8.0.0 */
#define RTE_FileSystem_Core             /* File System Core */
/* Keil::File System&MDK:Drive:USB@8.0.0 */
#define RTE_FileSystem_Drive_USB_0      /* File System USB Drive 0 */

/* Keil::USB&MDK:CORE@8.0.0 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Host:MSC@8.0.0 */
#define RTE_USB_Host_MSC                /* USB Host MSC */
/* Keil::USB&MDK:Host@8.0.0 */
#define RTE_USB_Host_0                  /* USB Host 0 */



#endif /* RTE_COMPONENTS_H */
